---
title: Vermont RSV Wastewater Monitoring
author: Jacob Pancoast
format:
    dashboard:
        orientation: columns
        nav-buttons: [linkedin, github]
        theme: [default, custom.scss]
server: shiny
---

```{r}
#| context: setup
#| echo: false
pacman::p_load(tidyverse,
               sf,
               shiny,
               shinyWidgets,
               leaflet)

rsv <- readRDS("data/rsv.rds")
flu_a <- readRDS("data/flu_a.rds")
covid <- readRDS("data/covid.rds")
measles <- readRDS("data/measles.rds")
mpox <- readRDS("data/mpox.rds")

geography <- readRDS("data/geography.rds")

```

``` {r}
#| context: server

# HTML UIs

output$year <- renderUI({
    HTML(paste0(
        "<h3>", "Year", "</h3>"
    ))
})

output$week <- renderUI({
    HTML(paste0(
        "<h3>", "Week", "</h3>",
        "<h5>", "ending ", selected_date(), "</h5>"
    ))
})

```

``` {r}
#| context: server

# Reactive to user input

selected_data <- reactive({

    req(input$disease)

    switch(
        input$disease,
        "RSV" = rsv,
        "Influenza A" = flu_a,
        "COVID-19" = covid
    )

})

years_of_data <- reactive({

    selected_data() |>
        filter(state_territory == 'vt') |>
        distinct(year = year(sample_collect_date)) |>
        arrange(desc(year)) |>
        pull(year)

})

min_date <- reactive({

    # Grab the minimum date from the entire data set
    selected_data() |>
        summarise(
            min_date = ceiling_date(min(sample_collect_date), unit = "week"),
        ) |>
        pull(min_date)

})

max_date <- reactive({

    # Grab max date
    selected_data() |>
        summarise(
            max_date = max(sample_collect_date)
        ) |>
        pull(max_date)

})

min_week <- reactive({

    # If selected year is the first one in the data, use that number of weeks
    min_week <- if (as.numeric(input$year) == year(min_date())) {
        week(min_date())
        } else { # Otherwise we are in a year that has a beginning so just use 1
            1
            }

})

max_week <- reactive({

    # If selected year is the current, unfinished year, use that number of weeks
    if (as.numeric(input$year) == year(max_date())) {
        week(max_date())
        } else { # Otherwise use 52 weeks for a past full year
            52
            }
})

wval_colors <- reactive({

    switch(
        input$disease,
        "RSV" = {
            c("Very Low" = "#d3ead2", 
            "Low" = "#a4c4a3", 
            "Moderate" = "#789f75", 
            "High" = "#4c7c49", 
            "Very High" = "#20591d")
        },
        "Influenza A" = {
            c("Very Low" = "#bfc2d9", 
            "Low" = "#969fc9", 
            "Moderate" = "#6d7db8", 
            "High" = "#425ba6", 
            "Very High" = "#153993")
        },
        "COVID-19" = {
            c("Very Low" = "#ead2d5", 
            "Low" = "#bd9da1", 
            "Moderate" = "#906b6f", 
            "High" = "#663c40", 
            "Very High" = "#3c1016")
        }
    )

})

palette <- reactive({

    colorFactor(
        palette = unname(wval_colors()),
        levels = names(wval_colors()),
        na.color = "#6b6969"
    )

})

```

``` {r}
#| context: server

# Update sliders when data changes
observe({
    updateSliderInput(
        session,
        "week",
        label = paste0("Week ending ", selected_date()),
        max = max_week(),
        min = min_week(),
        value = min(input$week, max_week())
        )

    updateSelectInput(
        session,
        "year",
        choices = years_of_data(), 
        selected = if_else(
            input$year %in% years_of_data(),
            as.numeric(input$year),
            max(years_of_data())
        )
    )
})

```

## Column

### {.toolbar}

``` {r}

selectInput(
    "disease",
    "Pathogen",
    choices = c("RSV", "Influenza A", "COVID-19"),
    selected = "RSV"
)

#htmlOutput("disease")

```

``` {r}

# Render text
#htmlOutput("year")

# Select year
selectInput(
    "year", 
    "Year", 
    choices = 0, # PLACEHOLDER DURING INIT
    selected = 0 # PLACEHOLDER DURING INIT
    )

```

``` {r}

# Render text
#htmlOutput("week")

# Select week
sliderInput(
    "week", 
    "Week ending", 
    min = 1, 
    max = 52, # PLACEHOLDER DURING INIT
    value = 52, # PLACEHOLDER DURING INIT
    step = 1,
    ticks = FALSE
    )

```

### Row

``` {r}

htmlOutput("state_summary")

```

``` {r}

htmlOutput("county_summary")

```

``` {r}
#| context: server

library(tidyverse)

output$plot <- renderPlot({

    # July of year 1 - June of year 2
    season_start <- if (month(selected_date()) <= 6) {
        # If we are before July of a year, starting season was the previous year
        year(selected_date()) - 1
    } else {
        # Otherwise, starting season will be this year
        year(selected_date())
    }

    # Filter data in this range
    filtered_data <- selected_data() |>

        # In the year range and only VT
        filter(
            state_territory == 'vt',
            counties_served == lower(selected_id()),
            sample_collect_date >= make_date(
                year = season_start,
                month = 7,
                day = 1
            ),
            sample_collect_date <= make_date(
                year = season_start + 1,
                month = 6,
                day = 30
            )
        ) |>

        group_by(sample_collect_date)

    # Return graph
    ggplot(
    data = filtered_data
    ) +
    geom_line(
        mapping = aes(
        x = sample_collect_date,
        y = pcr_target_avg_conc
        )
    ) + labs(
        title = paste0(
            season_start, "-", season_start + 1,
            " season"
            )
    )
})

output$heatmap <- renderPlot({

    # July of year 1 - June of year 2
    season_start <- if (month(selected_date()) <= 6) {
        # If we are before July of a year, starting season was the previous year
        year(selected_date()) - 1
    } else {
        # Otherwise, starting season will be this year
        year(selected_date())
    }

    # Filter data in this range
    filtered_data <- selected_data() |>

        # In the year range and only VT
        filter(
            state_territory == 'vt',
            sample_collect_date >= make_date(
                year = season_start,
                month = 7,
                day = 1
            ),
            sample_collect_date <= make_date(
                year = season_start + 1,
                month = 6,
                day = 30
            )
        ) |>

        mutate(
            month = format(sample_collect_date, "%Y-%m")
            ) |>

        summarise(
            concentration = mean(pcr_target_avg_conc, na.rm = TRUE),
            .by = c(month, counties_served)
        ) |>

        rename(county = counties_served) |>

        ungroup() |>

        left_join(filtered_data_step_4_5_for_heatmap(), by = c("county", "month")) |>

        mutate(
            wval = factor(
                categorize_wval(wval),
                levels = c(
                    "Very Low",
                    "Low",
                    "Moderate",
                    "High",
                    "Very High"
                )
            )
        )

    # Return graph
    ggplot(
    data = filtered_data
    ) +
    geom_tile(
        mapping = aes(
        x = month,
        y = county,
        fill = as.factor(wval)
        )
    ) + labs(
        title = paste0(
            season_start, "-", season_start + 1,
            " Season"
            ),
        y = "County",
        x = "Month",
        fill = "WVAL Classification"
    ) +
    scale_fill_manual(
        values = wval_colors(),
        na.value = "#6b6969"
    ) + theme_minimal() +
    theme(
        text = element_text(
            family = "Segoe UI"
        ),
        plot.title = element_text(
            hjust = 0.5,
            face = "bold",
            size = 1.1 * 16,
            color = "#808080"
        ),
    )
})

```

### Row {height=50%}

``` {r}

plotOutput("heatmap")

```

## Column

``` {r}

leafletOutput("map")

```

``` {r}
#| context: server

selected_date <- reactive({

    req(input$year, input$week)

    year_beginning = make_date(
        year = input$year,
        month = "01",
        day = "01"
    )

    ceiling_date(year_beginning + weeks(input$week - 1), unit = "week") - 1

})

selected_id <- reactiveVal("CHITTENDEN")

observeEvent(input$map_shape_click, {
    click <- input$map_shape_click

    if (!(is.null(selected_id())) && selected_id() == click$id) {
        selected_id(NULL)
    } else {
        selected_id(click$id)
    }
})

filtered_data_step_1_2 <- reactive({
    # Step 1 - Group data

    grouped <- selected_data() |>

        # Vermont only
        filter(state_territory == 'vt') |>

        # Group by each site
        group_by(site, counties_served) |>

        # Rename county column
        rename(county = counties_served)   

    # Step 2 - Validate data

    validated <- grouped |> 

        # Log transform the concentrations
        mutate(pcr_target_avg_conc = log1p(pcr_target_avg_conc),
        pcr_target_avg_conc_z_score = scale(pcr_target_avg_conc)) |>

        # Remove outliers
        filter(pcr_target_avg_conc_z_score <= 4)
    
})

filtered_data_step_3 <- reactive({
    # Step 3 - Determine low levels for each site

    filtered_data_step_1_2() |>

        # Only grab data from last 2 years
        filter(sample_collect_date > (if_else(
            month(max(sample_collect_date)) < 8,

            # If we are before August of curr year, use last year's August 1st
            make_date(year = year(max(sample_collect_date)) - 1, month = 8, day = 1),

            # If we are past August 1st of curr year, use this year's August 1st
            make_date(year = year(max(sample_collect_date)), month = 8, day = 1)) - years(2)
            )
        ) |>

        summarise(

            # 10th percentile
            baseline = quantile(pcr_target_avg_conc, probs = 0.1, na.rm = TRUE),

            # Std dev of concs (using 8 weeks of data, hence 56 days)
            std_dev = sd(pcr_target_avg_conc, na.rm = TRUE)

        )
})

filtered_data_step_4_5_for_individ <- reactive({

    # Step 4 // 5 - Compare current levels to baselines // Identify average and median values

    filtered_data_step_1_2() |>
        
        # Find the date closest to the input date to use as the "current amount of virus"
        summarise(
            
            # date of interest (DOT)
            date_of_interest = max(sample_collect_date[sample_collect_date <= selected_date() & !is.na(pcr_target_avg_conc)]),

            start_of_dot_week = floor_date(date_of_interest, "week", week_start = 7),

            week_of_interest_avg_conc = mean(
                pcr_target_avg_conc[sample_collect_date <= date_of_interest & sample_collect_date >= start_of_dot_week], 
                na.rm = TRUE
                )
            
            ) |>

        left_join(filtered_data_step_3(), by = c("county", "site")) |>

        group_by(county, site) |>

        summarise(wval = exp((week_of_interest_avg_conc - baseline) / std_dev)) |>

        ungroup() |>

        group_by(county) |>

        summarise(wval = median(wval, na.rm = TRUE),
            num_sites = n_distinct(site, na.rm = TRUE)) |>

        mutate(county = toupper(county)) |>

        ungroup() 
})

filtered_data_step_4_5_for_heatmap <- reactive({

    # Step 4 // 5 - Compare current levels to baselines // Identify average and median values

    filtered_data_step_1_2() |>

        ungroup() |>

        mutate(
            # all months
            month = format(sample_collect_date, "%Y-%m")
        ) |>
        
        # Find the date closest to the input date to use as the "current amount of virus"
        summarise(
            avg_concentration = mean(pcr_target_avg_conc, na.rm = TRUE),

            .by = c(month, county, site)
            
            ) |>

        left_join(filtered_data_step_3(), by = c("county", "site")) |>

        group_by(county, site, month) |>

        summarise(wval = exp((avg_concentration - baseline) / std_dev)) |>

        ungroup() |>

        group_by(county, month) |>

        summarise(wval = median(wval),
            num_sites = n_distinct(site, na.rm = TRUE)) |>

        ungroup()

})

categorize_wval <- function(wval) {
    return(
        case_when(
            wval > 11   ~ "Very High",
            wval > 8    ~ "High",
            wval > 5.2  ~ "Moderate",
            wval > 2.5  ~ "Low",
            wval > -Inf ~ "Very Low",
            is.na(wval) ~ "Not available",
            TRUE        ~ "ERROR"
        )
    )
}

output$map <- renderLeaflet({

        # Step 6 - Categorize values based on CDC cutoffs

        spatial <- geography |>

        left_join(filtered_data_step_4_5_for_individ(), by = join_by(CNTYNAME == county)) |>

        mutate(
            category = categorize_wval(wval)
            )

    leaflet(
        spatial,
        options = leafletOptions(
            scrollWheelZoom = FALSE,
            zoomControl = FALSE
            )
        ) |>

        addPolygons(
            layerId = ~CNTYNAME,
            fillColor = ~palette()(category),
            fillOpacity = 0.8,
            color = "white",
            weight = 1,
            label = ~paste0(CNTYNAME, ": ", category),
            highlightOptions = highlightOptions(weight = 3, color = "#666", bringToFront = TRUE)
        ) |>

        addPolygons(
            data = spatial |>
                filter(CNTYNAME == selected_id()),
            color = "black"
        )

    })

output$state_summary <- renderUI({

    # Filter and categorize (MAKE THIS A FUNCTION)
    median_wval <- filtered_data_step_4_5_for_individ() |>
        summarise(wval = round(median(wval, na.rm = TRUE), digits = 2)) |>
        pull(wval)
    
    median_wval <- categorize_wval(median_wval)

    # HTML for rendering
    HTML(paste0(
        "<h3>", "State", "</h3>",
        "<h2>", "VERMONT", "</h2>",
        "<h4>", selected_date(), "</h4>",
        "<p>", "Median WVAL: ", median_wval, "</p>"
    ))
    
})

output$county_summary <- renderUI ({

    # Filter and categorize (MAKE THIS A FUNCTION)
    selected_wval <- filtered_data_step_4_5_for_individ() |>
        filter(county == selected_id()) |>
        pull(wval)

    selected_wval <- categorize_wval(selected_wval)

    if (length(selected_wval) == 0) {
        selected_wval = NA
    }

    num_sites <- filtered_data_step_4_5_for_individ() |>
        filter(county == selected_id()) |>
        pull(num_sites)
    
    if (length(num_sites) == 0) {
        num_sites = 0
    }

    # HTML for rendering
    HTML(paste0(
        "<h3>", "County", "</h3>",
        "<h2>", selected_id(), "</h2>",
        "<h4>", selected_date(), "</h4>",
        "<p>", "Activity: ", selected_wval, " (", num_sites, " sites)", "</p>"
        ))

})

```
